version: '3.9'

services:
  backend:
    container_name: lan-shared-rooms-api-container
    build: ./backend
    environment:
      - PORT=80
      - BACKEND_DOMAIN=${BACKEND_DOMAIN}
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}

  frontend:
    container_name: lan-shared-rooms-app-container
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_DOMAIN=${BACKEND_DOMAIN}
    depends_on:
      - backend
    environment:
      - PORT=80

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend